version: '3'
services:
  zookeeper:
    container_name: 'zookeeper'
    image: zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: 'kafka'
    image: 'confluentinc/cp-kafka'
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
  api_gateway:
    container_name: 'api_gateway'
    build: './api_gateway'
    ports:
      - 4000:4000
  auth_service:
    container_name: 'auth_service'
    build: './auth_service'
    ports:
      - 4001:4001
  product_service:
    container_name: 'product_service'
    build: './product_service'
    ports:
      - 4002:4002
    depends_on:
      - kafka
      - zookeeper
  cart_service:
    container_name: 'cart_service'
    build: './cart_service'
    ports:
      - 4003:4003
    depends_on:
      - kafka
      - zookeeper
  order_service:
    container_name: 'order_service'
    build: './order_service'
    ports:
      - 4004:4004
    depends_on:
      - kafka
      - zookeeper